server {
    listen 80;
    server_name overview.klitscher.info localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";
    }

    location ~* \.(svg|png|jpg|webp|ico|woff2)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.json$ {
        expires -1;
        add_header Cache-Control "no-cache";
    }

    gzip on;
    gzip_types text/plain text/css application/javascript image/svg+xml application/json;
}